# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_appurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appurl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
