# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170207_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
