# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170207_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
